_commit: 0.0.2rc-131-g4aee5bf
_src_path: gh:bswck/skeleton
author: bswck
cli: false
copyright: Bartosz Sławecki
description: A ``singledispatch()`` for arguments that are classes annotated as specific
    types.
docs: true
email: bswck.dev@gmail.com
github: bswck
license: MIT
package: class_singledispatch
precommit: true
pypi: true
pypi_description: A ``singledispatch()`` for arguments that are classes annotated
    as specific types.
pypi_project_name: class-singledispatch
pypy: true
python: '3.8'
repo: class_singledispatch
rtd: class-singledispatch
tests: true
visibility: public
wip: false
